id: P004365
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5051
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་རྣམ་བཤད་ཐར་ལམ་གསལ་བྱེད། སྟོད་ཆ།
  author: ''
  volumes:
    baa8706c2036448aa69227b9d3d58533:
      image_group_id: I3CN5053
      title: ''
      volume_number: 1
      total_pages: 661
      base_file: v001.txt
